# This is a basic workflow to help you get started with Actions

name: My-GitHubFirstproject
env:
  App_name  : "MyFlask"
  Pack_name : "Flask deploy ver ${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "My_First_test"
  My_First_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Print Hello Message
        run : echo "Hello World from Testing job"
      
      - name: execute few commands
        run : |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "Application name : ${{ env.App_name}}"|

  My_First_deploy:
  # Runs a single command using the runners shell
    runs-on: ubuntu-latest
    needs: [My_First_test]
    steps:
      - name: Print Hello Massage
        run: echo "Hello World from my deploy"
        
      - name: Printing deployment package
        run : echo "deploy package name is ${{ env.Pack_name }}" 

      
